title: Jacob # your name (or website title) here
logo: "/images/Fishing Jacob.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br>
  Just a guy that likes to program
  <br>
  <a href="https://jakabe.github.io/Blog/">My Blog</a>
  <br>
  <a href="https://jakabe.github.io/correlationmatrix/"> My Correlation Matrix page </a>
  <br>
  <a href="https://jakabe.github.io/TaskBoard/">The Task Board</a>
  <br>
  
  <!--
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  //-->
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
