title: Jacob Wenger # your name (or website title) here
logo: "/images/Fishing Jacob.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br>
  Just a guy that likes to program
  <br>
  <a href="https://jakabe.github.io/projectsbyjakabe/"> My html site </a>
  <br>
  <a href="https://jakabe.github.io/correlationmatrix/"> My correlation matrix page </a>
  <br>
  <a href="https://jakabe.github.io/Silly_HTML_JS_Game/"> My Silly JavaScript Game </a>
  <br>
  <a href="https://jakabe.github.io/ToDoList/"> I made a To-Do list! Try it out!</a>
  <br>
  <a href="https://jakabe.github.io/TaskBoard/">I made an even bigger to-do list, with more lists! :)</a>
  <br>
  
  <!--
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  //-->
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
